backend:
  name: github
  repo: DVLrepertoire/songs
  branch: main
  auth_scope: repo
  client_id: Ov23liMwxM4SQ6X4hVHN
  base_url: https://dvlrepertoire.github.io/songs/admin/

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "songs"
    label: "Songs"
    folder: "_songs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
